---
title: "US Consumer Financial Complaints 2011-2019"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

## Loading libraries
library(flexdashboard)
library(shiny)
library(highcharter)
library(xts)
library(DT)
library(dplyr)
library(viridis)

## Loading data
mydata <- read.csv("./data/data.csv")
names(mydata) <- c("date_received","product","company","state","consumer_disputed.")

```


Inputs {.sidebar}
-----------------------------------------------------------------------

### Select Products

```{r shinyinputs}

## Setting the filter attribute
selectInput("product",  "Type of Product", unique(mydata$product))

```

### About

This R powered Shiny application lets you interactively view the financial complaints, time series plot and high level details of the Consumer Complaints.


### Data Source

Consumer Complaint Database maintained by Consumer Financial Protection Bureau. This bureau is a U.S. government agency that makes sure banks, lenders, and other financial companies treat you fairly




Row {data-height=700}
-----------------------------------------------------------------------

### 

```{r}

## Filtering the dataset based on the filter attribute
sample = reactive({
    mydata[mydata$product==input$product,]
})


## Creating the plot of map based on the number of complaints
renderHighchart({
  dshmstops <- data.frame(q = c(0, exp(1:5)/exp(5)),c = substring(viridis(5 + 1, option = "D"), 0, 7)) %>% 
  list_parse2()

  by_states <- sample() %>% group_by(state) %>% summarise(Total = n()) 
  by_states$statename <- state.name[match(by_states$state, state.abb)]
  by_states <- na.omit(by_states)

  plot1 <- (highchart() %>%
               hc_add_series_map(usgeojson, by_states, name = "Number of Complaints",
                                 value = "Total", joinBy = c("woename", "statename"),
                                 dataLabels = list(enabled = TRUE, format = '{point.name}'))  %>% 
               hc_colorAxis(stops = dshmstops) %>%
               hc_credits(enabled = TRUE, text = "Data Source :Consumer Complaint Database by Consumer Financial Protection Bureau") %>%
               hc_add_theme(hc_theme_google()) %>% 
               hc_mapNavigation(enabled = TRUE) 
               )
  
  plot1

})


```


### 

```{r}

## Creating timeseries plot of the number of complaints
sampletime = reactive({
    mysample = mydata[mydata$product==input$product,]
    mysample$date_received <- as.Date(mysample$date_received, format = "%m/%d/%Y")
    by_Date <- na.omit(mysample) %>% group_by(date_received) %>% summarise(Total = n())
    timeseries <- xts(by_Date$Total, order.by=as.POSIXct(by_Date$date_received))
    timeseries
})



renderHighchart({
  hchart(sampletime())
})      

```

Row {data-width=350}
-----------------------------------------------------------------------

### Number of Complaints {.value-box}

```{r}

sample = reactive({
    mydata[mydata$product==input$product,]
})

# Box with number of complaints
renderValueBox({
  valueBox(value = dim(sample())[1], icon = "fa-users", color = "red")
})
```


### Company with Most Complaints {.value-box}

```{r}

samplerow = reactive({
    head(mydata[mydata$product==input$product,] %>% group_by(company) %>% summarise(Total = n()) %>% arrange(desc(Total)) %>% head(1))[1]
})

# Box with company with most complaints.
renderValueBox({
  valueBox(value = samplerow(), icon = "fa fa-money", color = "blue")
})
```

### Number of Users Disputed {.value-box}

```{r}

sample = reactive({
    mydata[mydata$product==input$product,]
})

# Box with number of users disputed
renderValueBox({
  valueBox(value = table(sample()$consumer_disputed.)[2], icon = "fa fa-flag", color = "green")
})
```
